site_name: YukkiMoru's Portfolio
site_url: https://github.com/YukkiMoru/portfolio
copyright: "&copy; 2025-2026 Yukki_Moru"

theme:
  favicon: assets/logo/PF_NBG_small.ico
  logo: assets/logo/PF_NBG_small.ico
  name: material
  language: ja
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: ダークモードに切り替え
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: ライトモードに切り替え

  features:
    - navigation.instant
    - navigation.toc.integrate
    # - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.sections
    - navigation.expand
    # - navigation.top
    # - search.highlight
    # - search.suggest
    # - content.code.copy
  
  font:
    text: 'Noto Sans JP'
    code: 'Roboto Mono'

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.superfences

nav:
  - ホーム: index.md
  - プロジェクト: 
    - 自動運転AIチャレンジ: projects/automotive_ai_challenge.md
    - X-tech-Bridge: projects/meta_hide_and_seek.md
    - サポーターズ ハッカソン: projects/supporterz_hackathon.md
    - Kaggle: projects/kaggle.md
    - Cat Detection: projects/cat_detection.md
    - Minecraft Plugin: projects/minecraft_plugin.md
  - スキル: skills.md

extra:
  analytics:
    provider: google
    property: G-6S83NW7822