site_name: YukkiMoru's Portfolio
site_url: https://github.com/YukkiMoru/portfolio
copyright: "&copy; 2025-2026 Yukki_Moru"

theme:
  favicon: assets/logo/PF_NBG_small.ico
  logo: assets/logo/PF_NBG_small.ico
  name: material
  language: ja
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: ダークモードに切り替え
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: ライトモードに切り替え

  features:
    - navigation.instant
    - navigation.toc.integrate
    # - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.sections
    - navigation.expand
    # - navigation.top
    # - search.highlight
    # - search.suggest
    # - content.code.copy
  
  font:
    text: 'Noto Sans JP'
    code: 'Roboto Mono'

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.superfences

nav:
  - ホーム: index.md
  - プロジェクト: 
    - 自動運転AIチャレンジ: projects/automotive_ai_challenge/automotive_ai_challenge.md
    - X Tech Bridge: projects/X_Tech_Bridge/X_Tech_Bridge.md
    - ハッカソン:
      - ジョブマッチングSNS: projects/hackathon/jobmatch_sns/jobmatch_sns.md
      - ブックマーク コパイロット: projects/hackathon/bookmark_copilot/bookmark_copilot.md
    - コンペティション:
      - AIMO 2026: projects/competition/AIMO2026/AIMO2026.md
      - GCGC 2025: projects/competition/GCGC2025/GCGC2025.md
      - Santa 2025: projects/competition/Santa2025/Santa2025.md
    - 個人開発:
      - Cat Detection: projects/personal/cat_detection/cat_detection.md
      - Minecraft Plugin: projects/personal/minecraft_plugin/minecraft_plugin.md
  - スキル: skills.md

extra:
  analytics:
    provider: google
    property: G-6S83NW7822